import './globals.css'
import type { Metadata } from 'next'
import Header from '../components/Header'
import Footer from '../components/Footer'


export const metadata: Metadata = {
  title: 'Willamette Valley Water Polo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} >
        <Header />
          <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
